strategy:
  lookback: 20
  z_enter: 2.0
  z_exit: 0.5
  min_vol: 0.02
  max_holding: 10
data:
  start: '2020-01-01'  # Wider range for testing
  end: '2025-06-10'
  interval: '1d'
  min_vol: 100000  # Minimum daily volume per stock
tickers:
  universe: ['XOM', 'CVX', 'BP', 'SHEL', 'VLO', 'PSX', 'MPC', 'JPM', 'BAC', 'WFC', 'AAPL', 'MSFT', 'GOOGL']
  pair: ['XOM', 'CVX']
backtest:
  tc_per_trade: 0.0005  # 0.05% round-trip costs
  stop_loss: -0.05  # 5% stop-loss per trade
pair_selection:
  p_thresh: 0.05
  corr_thresh: 0.7
  vol_thresh: 1000000